apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: fast-delivery-dev
  labels:
    app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "Waiting for Redis..."
                sleep 2
              done
              echo "Redis is ready!"
        - name: wait-for-services
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z order-service 5001; do
                echo "Waiting for Order Service..."
                sleep 2
              done
              until nc -z delivery-service 5002; do
                echo "Waiting for Delivery Service..."
                sleep 2
              done
              until nc -z stock-service 5003; do
                echo "Waiting for Stock Service..."
                sleep 2
              done
              echo "All services are ready!"
      containers:
        - name: celery-worker
          image: tasks:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
          env:
            - name: TASK_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASK_QUEUE_NAME
            - name: TASK_QUEUE_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASK_QUEUE_BROKER_URL
            - name: TASK_QUEUE_RESULT_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASK_QUEUE_RESULT_BACKEND_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_SERVICE_URL
            - name: DELIVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DELIVERY_SERVICE_URL
            - name: STOCK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STOCK_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
