apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fast-delivery-dev
type: Opaque
stringData:
  DB_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: fast-delivery-dev
type: Opaque
stringData:
  INFLUXDB_TOKEN: "my-super-secret-token"
  DOCKER_INFLUXDB_INIT_PASSWORD: "password123"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "my-super-secret-token"
